apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: tt
  template:
    metadata:
      labels:
        app: tt
    spec:
      containers:
      - name: tt
        image: ghcr.io/nouzan/tt:nightly

