apiVersion: batch/v1
kind: Job
metadata:
  name: tt
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  template:
    metadata:
      name: tt-pod
    spec:
      containers:
      - name: tt
        image: ghcr.io/nouzan/tt:nightly-2021-05-26
      restartPolicy: Never
